### ISSUE TITLE
Current master is broken due to changes in ff@0.5.1

### ISSUE THREAD

**Issue by dignifiedquire** [filecoin-project/rust-fil-proofs#1011]
Various compile issues when installing fresh as seen below. This is due to the breaking change in https://github.com/zkcrypto/ff/pull/14 which was published as ff@0.5.1

We should pin all our dependencies that use `ff` to `=0.5.0` to avoid this issue.

```
error[E0276]: impl has stricter requirements than trait
   --> /home/finalitylabs/.cargo/registry/src/github.com-1ecc6299db9ec823/paired-0.16.0/src/bls12_381/fq.rs:473:10
    |
473 | #[derive(PrimeField)]
    |          ^^^^^^^^^^ impl has extra requirement `R: std::marker::Sized`
error[E0276]: impl has stricter requirements than trait
  --> /home/finalitylabs/.cargo/registry/src/github.com-1ecc6299db9ec823/paired-0.16.0/src/bls12_381/fq12.rs:44:5
   |
44 |     fn random<R: RngCore>(rng: &mut R) -> Self {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ impl has extra requirement `R: std::marker::Sized`
error[E0276]: impl has stricter requirements than trait
  --> /home/finalitylabs/.cargo/registry/src/github.com-1ecc6299db9ec823/paired-0.16.0/src/bls12_381/fq2.rs:93:5
   |
93 |     fn random<R: RngCore>(rng: &mut R) -> Self {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ impl has extra requirement `R: std::marker::Sized`
error[E0276]: impl has stricter requirements than trait
   --> /home/finalitylabs/.cargo/registry/src/github.com-1ecc6299db9ec823/paired-0.16.0/src/bls12_381/fq6.rs:104:5
    |
104 |     fn random<R: RngCore>(rng: &mut R) -> Self {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ impl has extra requirement `R: std::marker::Sized`
error[E0276]: impl has stricter requirements than trait
 --> /home/finalitylabs/.cargo/registry/src/github.com-1ecc6299db9ec823/paired-0.16.0/src/bls12_381/fr.rs:3:10
  |
3 | #[derive(PrimeField)]
  |          ^^^^^^^^^^ impl has extra requirement `R: std::marker::Sized`
```

**Comment by kigawas** [comment]
Don't escape from the problem. You can just add it like `fn random<R: RngCore + ?Sized>(rng: &mut R) -> Self`

**Comment by keyvank** [comment]
@kigawas Any idea how can we fix these?:
```
error[E0276]: impl has stricter requirements than trait
   --> src/bls12_381/fq.rs:446:10
    |
446 | #[derive(PrimeField)]
    |          ^^^^^^^^^^ impl has extra requirement `R: std::marker::Sized`

error[E0276]: impl has stricter requirements than trait
 --> src/bls12_381/fr.rs:3:10
  |
3 | #[derive(PrimeField)]
  |          ^^^^^^^^^^ impl has extra requirement `R: std::marker::Sized`
```

**Comment by kigawas** [comment]
https://github.com/zkcrypto/pairing/pull/108

see this

**Comment by keyvank** [comment]
@kigawas I applied those changes, 3 out of 5 errors are gone now, but I'm still getting those two errors. (I'm seeing those even in your `fix-rngcode-sized` branch)

**Comment by keyvank** [comment]
https://github.com/zkcrypto/ff/issues/17

**Comment by kigawas** [comment]
> @kigawas I applied those changes, 3 out of 5 errors are gone now, but I'm still getting those two errors. (I'm seeing those even in your `fix-rngcore-sized` branch)

Did you try using ff on github master?

**Comment by keyvank** [comment]
> > @kigawas I applied those changes, 3 out of 5 errors are gone now, but I'm still getting those two errors. (I'm seeing those even in your `fix-rngcore-sized` branch)
> 
> Did you try using ff on github master?

Yes, GitHub version is working. Crates.io version does not.

**Comment by dignifiedquire** [comment]
I am going to pin the version to 0.5.0 for now, given that there is still no new release of ff_derive and we can't have all our code be broken by this

**Comment by ebfull** [comment]
Hey, sorry about that. The latest versions of

* `ff` (0.5.2)
* `ff_derive` (0.4.1)
* `pairing` (0.15.1)

should work together correctly now.

**Comment by dignifiedquire** [comment]
@DrPeterVanNostrand could you take care of PRing these updates please?

**Comment by dignifiedquire** [comment]
fixed
